version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    groups:
      all-dependencies:
        patterns:
          - "*"