using System.Reflection;
using System.Text;
using System.Threading.RateLimiting;
using BlogMVC.Data;
using BlogMVC.Helpers;
using BlogMVC.Infrastructure.Interfaces;
using BlogMVC.Infrastructure.Providers;
using BlogMVC.Infrastructure.Repositories;
using BlogMVC.Models;
using BlogMVC.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using MongoDB.Driver;

var builder = WebApplication.CreateBuilder(args);

// --- Identity / SQLite ---
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ??
                       throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlite(connectionString));
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

// Email confirmation is skipped; new accounts are usable immediately (see AuthController.Register).
builder.Services.AddIdentity<IdentityUser, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

// Fails at startup (not at the first login) when Jwt:Key is missing or too short for HMAC-SHA256.
var jwtKey = builder.Configuration.GetRequiredJwtKey();

// JWT is the default so a plain [Authorize] authenticates with the bearer token, not Identity's cookie scheme.
builder.Services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    })
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],
            ValidAudience = builder.Configuration["Jwt:Audience"],
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };
    });

builder.Services.AddControllers();
builder.Services.AddProblemDetails();

// --- Authorization policies (permission claims, see BlogMVC.Data.Permissions; role->permission assignment
// is runtime-editable via IRoleService/RolesController, stored as AspNetRoleClaims) ---
builder.Services.AddAuthorizationBuilder()
    .AddPolicy(Permissions.Posts.Create, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Posts.Create))
    .AddPolicy(Permissions.Posts.CreateBulk, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Posts.CreateBulk))
    .AddPolicy(Permissions.Posts.EditPolicy, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Posts.EditOwn, Permissions.Posts.EditAny))
    .AddPolicy(Permissions.Posts.DeletePolicy, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Posts.DeleteOwn, Permissions.Posts.DeleteAny))
    .AddPolicy(Permissions.Users.ManageRoles, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Users.ManageRoles))
    .AddPolicy(Permissions.Roles.Manage, policy => policy
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireClaim(Permissions.ClaimType, Permissions.Roles.Manage));

// --- Swagger / OpenAPI (fed from the XML doc comments generated by GenerateDocumentationFile) ---
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory,
        $"{Assembly.GetExecutingAssembly().GetName().Name}.xml"));

    options.AddSecurityDefinition(JwtBearerDefaults.AuthenticationScheme, new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Description = "JWT bearer token, e.g. \"Bearer {token}\" (obtained from POST api/auth/login).",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT"
    });
    options.AddSecurityRequirement(document => new OpenApiSecurityRequirement
    {
        { new OpenApiSecuritySchemeReference(JwtBearerDefaults.AuthenticationScheme, document), [] }
    });
});

const string frontendCorsPolicy = "Frontend";
var corsAllowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];
builder.Services.AddCors(options =>
{
    options.AddPolicy(frontendCorsPolicy, policy =>
    {
        policy.WithOrigins(["http://localhost:5173", "http://localhost:4173", .. corsAllowedOrigins])
            .AllowAnyHeader()
            .AllowAnyMethod()
            .WithExposedHeaders("ETag");
    });
});

// --- Rate limiting (brute-force / mass-registration protection on api/auth) ---
builder.Services.AddOptions<AuthRateLimitSettings>()
    .Bind(builder.Configuration.GetSection("RateLimiting:Auth"))
    .Validate(s => s.PermitLimit > 0 && s.WindowSeconds > 0,
        "RateLimiting:Auth:PermitLimit and RateLimiting:Auth:WindowSeconds must be positive.")
    .ValidateOnStart();
builder.Services.AddRateLimiter(options =>
{
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    // Partitioned by client IP; behind a reverse proxy this needs UseForwardedHeaders, or all clients share one limit.
    options.AddPolicy(RateLimitPolicies.Auth, httpContext =>
    {
        var settings = httpContext.RequestServices.GetRequiredService<IOptions<AuthRateLimitSettings>>().Value;
        return RateLimitPartition.GetFixedWindowLimiter(
            httpContext.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = settings.PermitLimit,
                Window = TimeSpan.FromSeconds(settings.WindowSeconds),
                QueueLimit = 0
            });
    });
});

// --- MongoDB (blog post storage) ---
builder.Services.Configure<MongoDbSettings>(
    builder.Configuration.GetSection("MongoDb"));
var connectionStringMongoDb = builder.Configuration.GetSection("MongoDb").GetSection("ConnectionString").Value;
builder.Services.AddSingleton(new MongoClient(connectionStringMongoDb));

// --- Application services ---
// Singletons: stateless, just delegate to the MongoDB client.
builder.Services.AddSingleton<IPostService, PostService>();
builder.Services.AddSingleton<IDateTimeProvider, SystemDateTimeProvider>();
builder.Services.AddSingleton<IPostRepository, PostRepository>();
builder.Services.AddSingleton<ITokenProvider, TokenProvider>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IRoleService, RoleService>();

var app = builder.Build();

// Applies pending EF Core migrations, creating the Identity schema on a brand-new database file
// (e.g. a fresh Docker volume) before anything queries it.
await app.MigrateDatabaseAsync();

// Seeds predefined Identity roles and their default permission claims; existing roles are left untouched
// (see IdentityRoleSeederExtensions and IRoleService for runtime role/permission administration).
await app.SeedIdentityRolesAsync();

if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
    app.UseSwagger();
    app.UseSwaggerUI();
}
else
{
    app.UseExceptionHandler();
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseRouting();
app.UseCors(frontendCorsPolicy);
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();